routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('clinicas', 'ClinicaController');
//rutas para el USUARIO DOCTOR
Route::resource('doctors', 'DoctorController');

Route::resource('users', 'UserController');

Route::resource('clientes', 'ClienteController');

Route::resource('citas', 'CitaController');

Route::resource('secretarias','SecretariaController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//ruta para el admin del sitio
Route::get('/adminDoctores', 'DoctorController@adminDoctorsIndex');

app/Doctor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Doctor extends User
{
    //
    protected $fillable = [
        'name', 'email', 'apellidoPaterno', 'apellidoMaterno', 'telefono', 'domicilio',
        'especialidad', 'num_cedula', 'user_id',
    ];
}

app/Http/Controllers/DoctorController.php
<?php

namespace App\Http\Controllers;

use App\Doctor;
use App\Cliente;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class DoctorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($id)
    {
        //
        $doctores= Doctor::findOrFail($id);
        //dd($doctores);

        return view('doctors.index',compact('doctores'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('doctors.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $datosDoctor=request()->all();

        return response()->json($datosDoctor);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $doctor = Doctor::findOrFail($id);
        dd($doctor);
        return view('doctors.show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $doctores = Doctor::findOrFail($id);

        return view('doctors.edit', compact('doctores'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Cliente::destroy($id);

        return redirect('doctors');
    }

    public function adminDoctorsIndex(){
        $doctores= Doctor::all();
        return view('doctors.index', compact('doctores'));
    }
}

resources/views/doctors/create.blade.php
@extends('layouts.app')

@section('content')
<h1 class="title text-center">Registro de Doctor</h1>
<hr>
<form>
        <div class="form-group" class="w-50 justify-content-center" style="width:25%; margin:auto;">
          <label for="name">{{'Nombre'}}</label>
          <input type="text" class="form-control" name="name" id="name">

          <label for="apellidoPaterno">{{'Apellido Paterno'}}</label>
          <input type="text" class="form-control" name="apellidoPaterno" id="apellidoPaterno">

          <label for="apellidoMaterno">{{'Apellido Materno'}}</label>
          <input type="text" class="form-control" name="apellidoMaterno" id="apellidoMaterno">

          <label for="email">{{'Email'}}</label>
          <input type="email" class="form-control" name="email" id="email">

          <label for="telefono">{{'Telefono'}}</label>
          <input type="text" class="form-control" name="telefono" id="telefono">

          <label for="domicilio">{{'Domicilio'}}</label>
          <input type="text" class="form-control" name="domicilio" id="domicilio">

          <label for="especialidad">{{'Especialidad'}}</label>
          <input type="text" class="form-control" name="especialidad" id="especialidad">

          <label for="numCedula">{{'Numero de Cedula'}}</label>
          <input type="text" class="form-control" name="numCedula" id="numCedula">
          <br>

          <button type="submit" class="btn btn-primary">Registrar</button>

        </div>
      </form>
@endsection

resources/views/doctors/edit.blade.php
@extends('layouts.app')

@section('content')
<h1 class="title text-center">Editar de Doctores</h1>
<hr>
<form action="" method="POST">

        <div class="form-group" class="w-50 justify-content-center" style="width:25%; margin:auto;">
                <label for="name">{{'Nombre'}}</label>
        <input type="text" class="form-control" name="name" id="name" value="{{ $doctores->name }}">

                <label for="apellidoPaterno">{{'Apellido Paterno'}}</label>
                <input type="text" class="form-control" name="apellidoPaterno" id="apellidoPaterno" value="{{ $doctores->apellidoPaterno }}">

                <label for="apellidoMaterno">{{'Apellido Materno'}}</label>
                <input type="text" class="form-control" name="apellidoMaterno" id="apellidoMaterno" value="{{ $doctores-> apellidoMaterno }}">

                <label for="email">{{'Email'}}</label>
                <input type="email" class="form-control" name="email" id="email" value="{{ $doctores->email }}">

                <label for="telefono">{{'Telefono'}}</label>
                <input type="text" class="form-control" name="telefono" id="telefono" value="{{ $doctores->telefono }}">

                <label for="domicilio">{{'Domicilio'}}</label>
                <input type="text" class="form-control" name="domicilio" id="domicilio" value="{{ $doctores->domicilio }}">

                <label for="especialidad">{{'Especialidad'}}</label>
                <input type="text" class="form-control" name="especialidad" id="especialidad" value="{{ $doctores->especialidad }}">

                <label for="numCedula">{{'Numero de Cedula'}}</label>
                <input type="text" class="form-control" name="numCedula" id="numCedula" value="{{ $doctores->numCedula }}">
                <br>

                <button type="submit" class="btn btn-primary">Registrar</button>

              </div>
</form>
@endsection

resources/views/doctors/index.blade.php
@extends('layouts.app')

@section('content')
<h1 class="title text-center">Catalogo de Doctores</h1>
<hr>
<div class="w-50 justify-content-center" style="width:50%; margin:auto;">
    <a href="{{route('doctors.create')}}" class="btn btn-warning ">Agregar Doctor</a>
    <a href="{{route('clinicas.create')}}" class="btn btn-warning ">Agregar Clinica</a>
    <a href="{{route('secretarias.create')}}" class="btn btn-warning ">Agregar Secretaria</a>
</div>
<hr>
<div class="row justify-content-center">
        <div class="col-auto">
            <table class="table table-striped table-inverse  " align="center">
                <thead class="thead-inverse">
                    <tr>
                        <th>Nombre</th>
                        <th>A. Paterno</th>
                        <th>A. Materno</th>
                        <th>Especialidad</th>
                        <th>Num. Cedula</th>
                        <th colspan="3">Acciones</th>
                    </tr>
                    </thead>
                    <tbody>
                        @foreach ($doctores as $doctor)
                        <tr>
                                <td>{{ $doctor->name}}</td>
                                <td>{{ $doctor->apellidoPaterno}}</td>
                                <td>{{ $doctor->apellidoMaterno}}</td>
                                <td>{{ $doctor->especialidad}}</td>
                                <td>{{ $doctor->num_cedula}}</td>
                                <td><a href="{{route('doctors.edit',$doctor->id)}}" class="btn btn-success" >Editar</a></td>
                                <td><a href="{{route('doctors.show',$doctor->id)}}" class="btn btn-primary" >Detalles</a></td>
                                <td><a href="{{route('doctors.destroy',$doctor->id)}}" class="btn btn-danger" >Borrar</a></td>
                            </tr>
                        @endforeach
                    </tbody>
            </table>
        </div>
      </div>
@endsection

resources/views/doctors/show.blade.php
Seccion para Mostrar Doctores