routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('clinicas', 'ClinicaController');
//rutas para el USUARIO DOCTOR
Route::resource('doctors', 'DoctorController');

Route::resource('users', 'UserController');

Route::resource('clientes', 'ClienteController');

Route::resource('citas', 'CitaController');

Route::resource('secretarias','SecretariaController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//ruta para el admin del sitio
Route::get('/adminDoctores', 'DoctorController@adminDoctorsIndex');

app/Cliente.php
<?php

namespace App;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Cliente extends User
{

    protected $fillable = [
        'name', 'email', 'apellidoPaterno', 'apellidoMaterno', 'telefono', 'domicilio',
        'tipo_sangre', 'alergias', 'enfermedadesCronicas', 'user_id',
    ];

}

app/Http/Controllers/ClienteController.php
<?php

namespace App\Http\Controllers;

use App\Cliente;
use Illuminate\Http\Request;

class ClienteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $clientela= Cliente::all();

        return view('clientes.index',compact('clientela'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('clientes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $clientela = Cliente::findOrFail($id);

        return view('clientes.edit', compact('clientela'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Cliente::destroy($id);

        return redirect('clientes');
    }
}

resources/views/clientes/create.blade.php
Seccion para Insertar Clientes
@extends('layouts.app')

@section('content')
<h1 class="title text-center">Registro de Clientes</h1>
<hr>
<form>
        <div class="form-group" class="w-50 justify-content-center" style="width:25%; margin:auto;">
          <label for="name">{{'Nombre'}}</label>
          <input type="text" class="form-control" name="name" id="name">

          <label for="apellidoPaterno">{{'Apellido Paterno'}}</label>
          <input type="text" class="form-control" name="apellidoPaterno" id="apellidoPaterno">

          <label for="apellidoMaterno">{{'Apellido Materno'}}</label>
          <input type="text" class="form-control" name="apellidoMaterno" id="apellidoMaterno">

          <label for="email">{{'Email'}}</label>
          <input type="email" class="form-control" name="email" id="email">

          <label for="telefono">{{'Telefono'}}</label>
          <input type="text" class="form-control" name="telefono" id="telefono">

          <label for="domicilio">{{'Domicilio'}}</label>
          <input type="text" class="form-control" name="domicilio" id="domicilio">

          <label for="tipo_sangre">{{'Tipo de Sangre'}}</label>
          <input type="text" class="form-control" name="tipo_sangre" id="tipo_sangre">

          <label for="alergias">{{'Alergias'}}</label>
          <input type="text" class="form-control" name="alergias" id="alergias">

          <label for="enfermedadesCronicas">{{'Enfermedades Cronicas'}}</label>
          <input type="text" class="form-control" name="enfermedadesCronicas" id="enfermedadesCronicas">
          <br>

          <button type="submit" class="btn btn-primary">Registrar</button>

        </div>
      </form>
@endsection

resources/views/clientes/edit.blade.php
@extends('layouts.app')

@section('content')
<h1 class="title text-center">Editar de Clientes</h1>
<hr>
<form action="" method="POST">

        <div class="form-group" class="w-50 justify-content-center" style="width:25%; margin:auto;">
          <label for="name">{{'Nombre'}}</label>
        <input type="text" class="form-control" name="name" id="name" value="{{ $clientela->name }}">

          <label for="apellidoPaterno">{{'Apellido Paterno'}}</label>
          <input type="text" class="form-control" name="apellidoPaterno" id="apellidoPaterno" value="{{ $clientela->apellidoPaterno }}">

          <label for="apellidoMaterno">{{'Apellido Materno'}}</label>
          <input type="text" class="form-control" name="apellidoMaterno" id="apellidoMaterno" value="{{ $clientela->apellidoMaterno }}">

          <label for="email">{{'Email'}}</label>
          <input type="email" class="form-control" name="email" id="email" value="{{ $clientela->email }}">

          <label for="telefono">{{'Telefono'}}</label>
          <input type="text" class="form-control" name="telefono" id="telefono" value="{{ $clientela->telefono }}">

          <label for="domicilio">{{'Domicilio'}}</label>
          <input type="text" class="form-control" name="domicilio" id="domicilio" value="{{ $clientela->domicilio }}">

          <label for="tipo_sangre">{{'Tipo de Sangre'}}</label>
          <input type="text" class="form-control" name="tipo_sangre" id="tipo_sangre" value="{{ $clientela->tipo_sangre }}">

          <label for="alergias">{{'Alergias'}}</label>
          <input type="text" class="form-control" name="alergias" id="alergias" value="{{ $clientela->alergias }}">

          <label for="enfermedadesCronicas">{{'Enfermedades Cronicas'}}</label>
          <input type="text" class="form-control" name="enfermedadesCronicas" id="enfermedadesCronicas" value="{{ $clientela->enfermedadesCronicas }}">
          <br>

          <button type="submit" class="btn btn-primary">Registrar</button>

        </div>
      </form>
@endsection

resources/views/clientes/index.blade.php
@extends('layouts.app')

@section('content')
<h1 class="title text-center">Catalogo de Clientes</h1>
<hr>
<div class="w-50 justify-content-center" style="width:50%; margin:auto;">
    <a href="{{route('clientes.create')}}" class="btn btn-warning ">Agregar Cliente</a>
</div>
<hr>
<div class="row justify-content-center">
        <div class="col-auto">
            <table class="table table-striped table-inverse  " align="center">
                <thead class="thead-inverse">
                    <tr>
                        <th>Nombre</th>
                        <th>A. Paterno</th>
                        <th>A. Materno</th>
                        <th>Tipod de Sandre</th>
                        <th>Alergias</th>
                        <th>Enfermedades Cronicas</th>
                        <th colspan="3">Acciones</th>
                    </tr>
                    </thead>
                    <tbody>
                        @foreach ($clientela as $cliente)
                        <tr>
                                <td>{{ $cliente->name}}</td>
                                <td>{{ $cliente->apellidoPaterno}}</td>
                                <td>{{ $cliente->apellidoMaterno}}</td>
                                <td>{{ $cliente->tipo_sangre}}</td>
                                <td>{{ $cliente->alergias}}</td>
                                <td>{{ $cliente->enfermedadesCronicas}}</td>
                                <td><a href="{{route('clientes.edit',$cliente->id)}}" class="btn btn-success" >Editar</a></td>
                                <td><a href="{{route('clientes.show',$cliente->id)}}" class="btn btn-primary" >Detalles</a></td>
                                <td><a href="{{route('clientes.destroy',$cliente->id)}}" class="btn btn-danger" >Borrar</a></td>
                            </tr>
                        @endforeach
                    </tbody>
            </table>
        </div>
      </div>
@endsection

resources/views/clientes/show.blade.php
Seccion para Mostrar clientes