routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('clinicas', 'ClinicaController');
//rutas para el USUARIO DOCTOR
Route::resource('doctors', 'DoctorController');

Route::resource('users', 'UserController');

Route::resource('clientes', 'ClienteController');

Route::resource('citas', 'CitaController');

Route::resource('secretarias','SecretariaController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//ruta para el admin del sitio
Route::get('/adminDoctores', 'DoctorController@adminDoctorsIndex');

app/Cita.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cita extends Model
{
    //
    protected $fillable = [
        'fechacita', 'horaCita', 'clinica_id', 'cliente_id',
    ];
}

app/Http/Controllers/CitaController.php
<?php

namespace App\Http\Controllers;

use App\Cita;
use Illuminate\Http\Request;

class CitaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $citaTomada = Cita::all();

        return view('citas.index',compact('citaTomada'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('citas.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/citas/create.blade.php
@extends('layouts.app')

@section('content')
<h1 class="title text-center">Registro de Citas</h1>
<hr>
<form>
        <div class="form-group" class="w-50 justify-content-center" style="width:25%; margin:auto;">
          <label for="fechaCita">{{'Fecha de Cita'}}</label>
          <input type="date" class="form-control" name="fechaCita" id="fechaCita">

          <label for="HoraCita">{{'Hora de Cita'}}</label>
          <input type="time" class="form-control" name="HoraCita" id="HoraCita">
          <br>

          <button type="submit" class="btn btn-primary">Registrar</button>

        </div>
      </form>
@endsection

resources/views/citas/edit.blade.php
Seccion para Editar Citas

resources/views/citas/index.blade.php
Seccion de Index de Citas
@extends('layouts.app')

@section('content')
<h1 class="title text-center">Catalogo de Citas</h1>
<hr>
<div class="w-50 justify-content-center" style="width:50%; margin:auto;">
    <a href="{{route('citas.create')}}" class="btn btn-warning ">Agregar Cita</a>
</div>
<hr>
<div class="row justify-content-center">
        <div class="col-auto">
            <table class="table table-striped table-inverse  " align="center">
                <thead class="thead-inverse">
                    <tr>
                        <th>Eliga la Fecha</th>
                        <th>Eliga la Hora</th>
                        <th colspan="3">Acciones</th>
                    </tr>
                    </thead>
                    <tbody>
                        @foreach ($citaTomada as $cita)
                        <tr>
                                <td>{{ $cita->fechaCita}}</td>
                                <td>{{ $cita->fechaCita}}</td>
                                <td><a href="{{route('citas.edit',$cita->id)}}" class="btn btn-success" >Editar</a></td>
                                <td><a href="{{route('citas.show',$cita->id)}}" class="btn btn-primary" >Detalles</a></td>
                                <td><a href="{{route('citas.destroy',$cita->id)}}" class="btn btn-danger" >Borrar</a></td>
                            </tr>
                        @endforeach
                    </tbody>
            </table>
        </div>
      </div>
@endsection

resources/views/citas/show.blade.php
Seccion para Mostrar Detalles de Citas