routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('clinicas', 'ClinicaController');
//rutas para el USUARIO DOCTOR
Route::resource('doctors', 'DoctorController');

Route::resource('users', 'UserController');

Route::resource('clientes', 'ClienteController');

Route::resource('citas', 'CitaController');

Route::resource('secretarias','SecretariaController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//ruta para el admin del sitio
Route::get('/adminDoctores', 'DoctorController@adminDoctorsIndex');

app/Clinica.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Clinica extends Model
{
    //
    protected $fillable = [
        'doctor_id', 'cita_id', 'secretaria_id', 'nombre', 'calle', 'codigoPostal', 'longitud',
        'latitud', 'fraccionamiento'. 'numero', 'numeroInterior', 'telefono', 'correoClinica',
        'imagen',
    ];
}

app/Http/Controllers/ClinicaController.php
<?php

namespace App\Http\Controllers;

use App\Clinica;
use Illuminate\Http\Request;

class ClinicaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        //return view('clinicas.index');
        $consultorios= Clinica::all();

        return view('clinicas.index',compact('consultorios'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('clinicas.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

        //$datosClinica=request()->all();

        $datosClinica=request()->except('_token');

        if($request->hasFile('imagen')){

            $datosClinica['imagen']=$request->file('imagen')->store('uploads', 'public');
        }

        Clinica::insert($datosClinica);

        return response()->json($datosClinica);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        return view('clinicas.show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        return view('clinicas.edit');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/clinicas/create.blade.php
Seccion para crear clinicas
<br><br>

<form action="{{ url('/clinicas')}}" method="POST" enctype="multipart/form-data">

    {{ csrf_field() }}
    <label for="Nombre">{{'Nombre Clinica'}}</label>
    <input type="text" name="Nombre" id="Nombre" value="">
    <br>

    <label for="Calle">{{'Calle'}}</label>
    <input type="text" name="Calle" id="Calle" value="">
    <br>

    <label for="CodigoPostal">{{'Codigo Postal'}}</label>
    <input type="text" name="CodigoPostal" id="CodigoPostal" value="">
    <br>

    <label for="Fraccionamiento">{{'Fraccionamiento'}}</label>
    <input type="text" name="Fraccionamiento" id="Fraccionamiento" value="">
    <br>

    <label for="Numero">{{'Numero'}}</label>
    <input type="text" name="Numero" id="Numero" value="">
    <br>

    <label for="NumeroInterior">{{'Numero Interior'}}</label>
    <input type="text" name="NumeroInterior" id="NumeroInterior" value="">
    <br>

    <label for="Telefono">{{'Telefono'}}</label>
    <input type="text" name="Telefono" id="Telefono" value="">
    <br>

    <label for="CorreoClinica">{{'Correo Clinica'}}</label>
    <input type="email" name="CorreoClinica" id="CorreoClinica" value="">
    <br>

    <label for="Imagen">{{'Imagen Clinica'}}</label>
    <input type="file" name="Imagen" id="Imagen" value="">
    <br>

    <input type="submit" value="Agregar">

</form>

resources/views/clinicas/index.blade.php
@extends('layouts.app')

@section('content')
<h1 class="title text-center">Catalogo de Clinicas</h1>
<hr>
<div class="w-50 justify-content-center" style="width:50%; margin:auto;">
    <a href="{{route('clinicas.create')}}" class="btn btn-warning ">Agregar Clinica</a>
</div>
<hr>
<div class="row justify-content-center">
        <div class="col-auto">
            <table class="table table-striped table-inverse  " align="center">
                <thead class="thead-inverse">
                    <tr>
                        <th>Nombre Clinica</th>
                        <th>Calle</th>
                        <th>Cod. Postal</th>
                        <th>Fraccionamiento</th>
                        <th>Numero</th>
                        <th>Num. Interior</th>
                        <th>Telefono</th>
                        <th>Correo</th>
                        <th>Imagen de Clinica</th>
                        <th colspan="3">Acciones</th>
                    </tr>
                    </thead>
                    <tbody>
                        @foreach ($consultorios as $clinica)
                        <tr>
                                <td>{{ $clinica->nombre}}</td>
                                <td>{{ $clinica->calle}}</td>
                                <td>{{ $clinica->codigoPostal}}</td>
                                <td>{{ $clinica->fraccionamiento}}</td>
                                <td>{{ $clinica->numero}}</td>
                                <td>{{ $clinica->numeroInterior}}</td>
                                <td>{{ $clinica->telefono}}</td>
                                <td>{{ $clinica->correoClinica}}</td>
                                <td>{{ $clinica->imagen}}</td>
                                <td><a href="{{route('clinicas.edit',$clinica->id)}}" class="btn btn-success" >Editar</a></td>
                                <td><a href="{{route('clinicas.show',$clinica->id)}}" class="btn btn-primary" >Detalles</a></td>
                                <td><a href="{{route('clinicas.destroy',$clinica->id)}}" class="btn btn-danger" >Borrar</a></td>
                            </tr>
                        @endforeach
                    </tbody>
            </table>
        </div>
      </div>
@endsection